Repository vapor/postgres-kit, pull requests merged in 2019-12, with the labels that each got.

#158 beta.2
  .github/workflows/test.yml
  Package.swift
  Tests/LinuxMain.swift
  Tests/PostgresKitTests/XCTestManifests.swift
Labels: enhancement

#160 array coding support; fix fatal errors
  Sources/PostgresKit/PostgresDataDecoder.swift
  Sources/PostgresKit/PostgresDataEncoder.swift
Labels: bug

#159 Custom JSON Coders for Postgres Data Coders
  Sources/PostgresKit/ConnectionPool+Postgres.swift
  Sources/PostgresKit/PostgresClient+SQL.swift
  Sources/PostgresKit/PostgresConfiguration.swift
  Sources/PostgresKit/PostgresDataDecoder.swift
  Sources/PostgresKit/PostgresDataEncoder.swift
  Sources/PostgresKit/PostgresRow+SQL.swift
Labels: enhancement

#161 postgres data encoder refactor
  .github/workflows/test.yml
  Sources/PostgresKit/PostgresDataDecoder.swift
  Sources/PostgresKit/PostgresDataEncoder.swift
  Sources/PostgresKit/PostgresRow+SQL.swift
  Tests/PostgresKitTests/PostgresKitTests.swift
Labels: bug, enhancement

#162 row.contains nil fix
  Sources/PostgresKit/PostgresRow+SQL.swift
  Tests/PostgresKitTests/PostgresKitTests.swift
Labels: bug
