Repository vapor/postgres-kit, pull requests merged in 2020-02, with the labels that each got.

#170 Add support for configuring connections via UNIX domain socket
  Sources/PostgresKit/PostgresConfiguration.swift
Labels: enhancement, semver-minor

#169 Added create/drop trigger dialect conditions
  Sources/PostgresKit/PostgresDialect.swift
  docker-compose.yml
Labels: enhancement, semver-minor

#172 support encoding arrays other than json
  .github/workflows/test.yml
  Sources/PostgresKit/PostgresDataDecoder.swift
  Sources/PostgresKit/PostgresDataEncoder.swift
Labels: bug, semver-patch

#173 Alter table syntax
  Sources/PostgresKit/PostgresDialect.swift
Labels: enhancement, semver-minor

#174 Release Candidate 1
  .github/workflows/test.yml
  Package.swift
  README.md
Labels: enhancement
